site_name: Apugli Documentation
nav:
    - Home: index.md
    - General Types:
      - Data Types: types/data_types.md
      - Power Types: types/power_types.md
    - Condition Types:
      - Damage Conditions: types/damage_conditions_types.md
      - Entity Conditions: types/entity_conditions_types.md
    - Action Types:
      - Block Actions: types/block_action_types.md
      - Entity Actions: types/entity_action_types.md
    - Miscellaneous:
      - Base Contents: misc/base_contents.md
      - Modded Damage Sources: misc/modded_damage_sources.md
      - Modded Sounds: misc/modded_sounds.md
      - Resource Bars: misc/resource_bars.md
      - Status Effects: misc/effects.md
theme: readthedocs
markdown_extensions:
    - toc:
        separator: "_"
    - admonition