site_name: Apugli Documentation
site_url: https://apugli.readthedocs.io
nav:
  - Home: index.md
  - General Types:
    - Data Types: types/data_types.md
    - Power Types: types/power_types.md
  - Condition Types:
    - Bi-entity Condition Types: types/bientity_condition_types.md
    - Damage Condition Types: types/damage_condition_types.md
    - Entity Condition Types: types/entity_condition_types.md
    - Item Condition Types: types/item_condition_types.md
  - Action Types:
    - Bi-entity Action Types: types/bientity_action_types.md
    - Block Action Types: types/block_action_types.md
    - Entity Action Types: types/entity_action_types.md
  - Miscellaneous:
    - Base Contents: misc/base_contents.md
    - Modded Damage Sources: misc/modded_damage_sources.md
    - Modded Sounds: misc/modded_sounds.md
    - Resource Bars: misc/resource_bars.md
    - Status Effects: misc/effects.md
theme:
  name: material
  features:
    - content.code.annotate
    - navigation.expand
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: green
      accent: light-green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode  
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: green
      accent: light-green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode  
  logo: images/logo.png
  favicon: images/logo.png
extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/MerchantPug/apugli
        name: Apugli GitHub
      - icon: fontawesome/brands/discord
        link: https://discord.gg/UBfEjsANNz
        name: Pug's Modzone Discord
markdown_extensions:
    - toc:
        separator: "_"
    - pymdownx.highlight:
        anchor_linenums: true
    - admonition
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences