site_name: Apugli Documentation
nav:
    - Home: index.md
    - Types:
      - Power Types: power_types.md
    - Conditions:
      - Damage Conditions: damage_conditions.md
      - Entity Conditions: entity_conditions.md
    - Actions:
      - Block Actions: block_actions.md
      - Entity Actions: entity_actions.md
    - Miscellaneous:
      - Modded Damage Sources: misc/modded_damage_sources.md
      - Modded Sounds: misc/modded_sounds.md
      - Origins: misc/origins.md
      - Powers: misc/powers.md
      - Resource Bars: misc/resource_bars.md
      - Status Effects: misc/status_effects.md
theme: readthedocs
separator: '_'